### ISSUE TITLE
安装错误+无法运行

### ISSUE THREAD

**Issue by enokoneko** [FromEndWorld/lofter2Jekyll#2]
macOS运行 `npm install lofter2jekyll -g`
提醒
> npm WARN deprecated to-markdown@3.0.0: to-markdown has been renamed to Turndown, with a new API. Please update to turndown v4.0.0 or above and see the migration guide for details: https://github.com/domchristie/turndown/wiki/Migrating-from-to-markdown-to-Turndown
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

然后运行readxml会显示`env: node\r: No such file or directory`

**Comment by FromEndWorld** [comment]
谢谢，报错信息很有帮助，我会更新到turndown

**Comment by FromEndWorld** [comment]
已更新到turndown
